controller_list:
  - name: fake_Set-completo_controller
    joints:
      - link_01__link_02
      - link_02__link_03
initial:  # Define initial robot poses.
  - group: Set-completo
    pose: Descanso